server:
  port: 0
spring:
  application:
    name: service-product
  data:
    mongodb:
      database: Banca
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true