server:
  port: 8099

spring:
  cloud:
    gateway:
      routes:
      - id: product
        uri: lb://service-product
        predicates:
          - Path=/listProducts/**
          
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
