server:
  port: 8099
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: product
        uri: lb://service-product
        predicates:
          - Path=/service-product/**